Resources:
  Address:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: UserId
          AttributeType: S
      KeySchema:
        - AttributeName: UserId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: Tu_Test_TableName
  GetCustomerAddressLambdaHandler:
    Type: AWS::Lambda::Function
    Properties:
      Handler: getHandler.handler
      Role: 
        Fn::GetAtt:
          - GetCustomerAddressLambdaHandlerRole21E6DA9B
          - Arn
      Code:
        S3Bucket: tu-stack-artifactbucket-xxxx
        S3Key: BasictestStack/getHandler/xxxxxxxx
      Runtime: nodejs14.x
      Environment:
        Variables:
          TABLE_NAME: 
            Ref: Address
    Metadata:
      'aws:cdk:path': BasictestStack/GetCustomerAddressLambdaHandler
  PutCustomerAddressLambdaHandler:
    Type: AWS::Lambda::Function
    Properties:
      Handler: saveHandler.handler
      Role: 
        Fn::GetAtt:
          - PutCustomerAddressLambdaHandlerRole92F30B4A
          - Arn
      Code:
        S3Bucket: tu-stack-artifactbucket-xxxx
        S3Key: BasictestStack/saveHandler/xxxxxxxx
      Runtime: nodejs14.x
      Environment:
        Variables:
          TABLE_NAME: 
            Ref: Address
    Metadata:
      'aws:cdk:path': BasictestStack/PutCustomerAddressLambdaHandler
  TuTestApiF56AD052:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: Tu_testApi
    Metadata:
      'aws:cdk:path': BasictestStack/TuTestApi/Resource
  userAddress0B79FAD4:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: 
        Fn::GetAtt:
          - TuTestApiF56AD052
          - RootResourceId
      PathPart: userAddress
      RestApiId: 
        Ref: TuTestApiF56AD052
    Metadata:
      'aws:cdk:path': BasictestStack/userAddress/Resource
  GetUserAddressApiGatewayMethodF09E83B7:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      ResourceId: 
        Ref: userAddress0B79FAD4
      RestApiId: 
        Ref: TuTestApiF56AD052
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: 
          Fn::Join:
            - ''
            - - 'arn:'
              - Ref: 'AWS::Partition'
              - ':apigateway:'
              - Ref: 'AWS::Region'
              - ':lambda:path/2015-03-31/functions/'
              - !GetAtt 
                - GetCustomerAddressLambdaHandler
                - Arn
              - /invocations
    Metadata:
      'aws:cdk:path': BasictestStack/userAddress/GET/Method
  PostUserAddressApiGatewayMethod5EB3F4F8:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: POST
      ResourceId: 
        Ref: userAddress0B79FAD4
      RestApiId: 
        Ref: TuTestApiF56AD052
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: 
          Fn::Join:
            - ''
            - - 'arn:'
              - Ref: 'AWS::Partition'
              - ':apigateway:'
              - Ref: 'AWS::Region'
              - ':lambda:path/2015-03-31/functions/'
              - !GetAtt 
                - PutCustomerAddressLambdaHandler
                - Arn
              - /invocations
    Metadata:
      'aws:cdk:path': BasictestStack/userAddress/POST/Method
  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: tuApiKey
      Value: thisIsJustSampleAPi123
    Metadata:
      'aws:cdk:path': BasictestStack/ApiKey
  APIURL:
    Type: AWS::CloudFormation::Output
    Properties:
      Value: 
        Fn::Join:
          - ''
          - - 'https://'
            - Ref: 'TuTestApiF56AD052'
            - '.execute-api.'
            - Ref: 'AWS::Region'
            - '.'
            - Ref: 'AWS::URLSuffix'
            - '/prod/'
    Metadata:
      'aws:cdk:path': BasictestStack/APIURL
