name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger pipeline on push to the main branch
      - development  # Also trigger pipeline on push to the development branch
  pull_request:
    branches:
      - main  # Trigger pipeline on pull requests to the main branch
      - development  # Also trigger pipeline on pull requests to the development branch

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        npm install  # Adjust based on your project's requirements

    - name: Run Tests
      run: |
        npm test  # Adjust based on your testing framework

  deploy:
    name: Deploy to AWS Lambda (Development)
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/development'  # Only deploy on changes to development branch

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: <your-aws-region>

    - name: Deploy with SAM
      run: |
        sam build
        sam deploy --stack-name <stack-name> --s3-bucket <your-s3-bucket> --capabilities CAPABILITY_IAM
