name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger pipeline on push to the main branch
      - develop  # Also trigger pipeline on push to the development branch
  pull_request:
    branches:
      - main  # Trigger pipeline on pull requests to the main branch
      - develop  # Also trigger pipeline on pull requests to the development branch

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        npm install  # Adjust based on your project's requirements

    # - name: Run Tests
    #   run: |
    #     npm test  # Adjust based on your testing framework

  deploy:
    name: Deploy to AWS using CDK (develop)
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/develop'  # Only deploy on changes to development branch

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js (if needed)  # Optional step if Node.js is not pre-installed
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'  # Or a compatible version for your npm

      - name: Install AWS CDK CLI
        uses: aws-actions/aws-cdk@v1  # This action installs CDK
        with:
          aws-region: ap-southeast-2  # Replace with your AWS region
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy Stack with CDK
        run: cdk deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name BasictestStack
